#datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bilibili
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    #????
    application:
      name: bilibili
#???
server:
  port: 8081


