#profile
spring:
  profiles:
    active: test
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.bilibili.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
